export const $mainContainer = document.getElementById("container");
export const $bodyContainer = document.getElementById("bodyContainer");
export const $taskInput = document.getElementById("taskInput");
export const $searchInput = document.getElementById("searchInput");
export const $addButton = document.getElementById("addButton");
export const $searchButton = document.getElementById("searchButton");
export const $taskList = document.getElementById("tasks");
export const $toaster = document.getElementById("message");
export const $toastBox = document.getElementById("toastContainer");
export const $splash = document.getElementById("splashScreen");
export const $noTask = document.getElementById("centeredImage");
export const $taskListContainer = document.getElementById("tasksContainer");
export const $loadMore = document.getElementById("loadMoreButton");
export const $createButton = document.getElementById("createButton");
export const $taskAddBox = document.getElementById("inputContainer");
export const $filterAllButton = document.getElementById("filterAll");
export const $filterIncompleteButton =
  document.getElementById("filterIncomplete");
export const $filterCompleteButton = document.getElementById("filterComplete");
